
# Site settings
title: Hanwei ZHANG
name: Hanwei ZHANG
subtitle: Ph. D student
email: hanwei.zhang@irisa.fr
description: >
  Ph.D student in Computer Science
baseurl: ""
url: "https://badchild0912.github.io/"
github_username:  badchild0912
disqus_baseurl: "https://badchild0912.github.io/"
disqus_shortname: https-badchild0912-github-io
permalink: :title

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Hanwei ZHANG"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: pesoto
    url: https://github.com/badchild0912
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Hanwei ZHANG
    url: https://www.linkedin.com/in/hanwei-zhang-247a29157/
    desc: Connect with me on LinkedIn
    share: true
